# TODO improve and update linters as the app is built
run:
  timeout: 5m
  skip-dirs:
    - .github

linters:
  enable:
    - asciicheck
    - deadcode
    - revive
    - gosimple
    - govet
    - ineffassign
    - errname
    - errorlint
    - stylecheck
    - structcheck
    - gosec
    - prealloc
    - unparam
    - unused
    - whitespace
    - ifshort
    - unconvert
  disable:
    - errcheck

linters-settings:
  gosec: {}
