FROM node:17.7-alpine3.15

RUN apk add -U curl

RUN curl -fsSL "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" -o /bin/pnpm; chmod +x /bin/pnpm;

COPY package.json .
COPY pnpm-lock.yaml .

RUN pnpm install
